
tasks:
  - init: ./gradlew build

vscode:
  extensions:
    - MS-CEINTL.vscode-language-pack-ja
    - GitHub.github-vscode-theme
    - Equinusocio.vsc-material-theme-icons
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
